os: linux
arch: amd64
dist: focal
language: clojure
cache:
  directories:
  - node_modules
  - $HOME/.m2
services:
  - postgresql
  - mysql
addons:
  apt:
    packages:
      - nodejs
      - leiningen
jobs:
  include:
  - name: "unit tests"
    env: TEST_SUITE=unit
  - name: "sqlite"
    env: TEST_SUITE=sqlite
  - name: "mysql"
    env: TEST_SUITE=mysql
  - name: "postgres"
    env: TEST_SUITE=postgres
install: ./.travis-scripts/install.sh $TEST_SUITE
script: ./.travis-scripts/run-tests.sh $TEST_SUITE
